In [9]:
#pip install openpyxl

In [12]:
import pandas as pd

xl = pd.DataFrame(pd.read_excel( 'data/combined_pose_data.xlsx'))
# Convert and save to CSV
xl.to_csv('data/combined_pose_data.csv', index=False)

In [13]:
df = pd.read_csv('data/combined_pose_data.csv')
df.head()

,class_name,metadata,x1,y1,z1,v1,x2,y2,z2,v2,...,z32,v32,x33,y33,z33,v33,x34,y34,z34,v34
0,ayesha,"spin, true_grip",0.550901532173157,0.452469408512116,-0.371652334928513,0.999634027481079,0.551996767520905,0.459261238574982,-0.373692780733109,0.999179065227509,...,0.484908133745194,0.711136996746063,0.431104391813278,0.247272819280624,-0.227218180894852,0.988907516002655,0.431104391813278,0.247272819280624,-0.227218180894852,0.988907516002655
1,ayesha,"spin, true_grip",0.550313651561737,0.456584453582764,-0.408107221126556,0.999585211277008,0.551725804805756,0.462751150131226,-0.418755561113358,0.99914014339447,...,0.744754374027252,0.718097865581513,0.450083166360855,0.246959403157234,0.100605793297291,0.989433228969574,0.450083166360855,0.246959403157234,0.100605793297291,0.989433228969574
2,ayesha,"spin, true_grip",0.550200760364533,0.460396617650986,-0.407223522663116,0.999601304531097,0.551819682121277,0.466391950845718,-0.416219681501389,0.999173760414124,...,0.815191566944122,0.715532183647156,0.466189026832581,0.248627513647079,0.263333767652512,0.989323079586029,0.466189026832581,0.248627513647079,0.263333767652512,0.989323079586029
3,ayesha,"spin, true_grip",0.554080247879028,0.459564983844757,-0.400975495576859,0.999601781368256,0.554280340671539,0.465722143650055,-0.408863842487335,0.999175667762756,...,0.705523192882538,0.724246919155121,0.511983454227448,0.253052622079849,0.0986333563923836,0.988872647285461,0.511983454227448,0.253052622079849,0.0986333563923836,0.988872647285461
4,ayesha,"spin, true_grip",0.55398041009903,0.459447383880615,-0.382720917463303,0.999635696411133,0.555034399032593,0.465176969766617,-0.380493581295013,0.999244153499603,...,0.567162215709686,0.737097322940826,0.53110146522522,0.253462135791779,-0.137917727231979,0.98934006690979,0.53110146522522,0.253462135791779,-0.137917727231979,0.98934006690979

In [14]:
delete_cols = ['x34', 'y34', 'z34', 'v34']
df = df.drop(columns=delete_cols, errors='ignore')
df.to_csv('data/combined_pose_data.csv', index=False)